### PR TITLE
Recipes for building packages using both PyInstaller and fpm.

### PR DESCRIPTION
**Pull request by tetron**
Two different recipes for building packages on Linux: using `PyInstaller`, and using `fpm`.

Haven't tried on Windows yet, and I don't have access to MacOS.

### CODE REVIEW

**Comment by kaushik-work** [comment]
@tetron this is fabulous. Thank you!

1. Is the distribution the zipped folder that this produces? Where should the user place this folder?
2. When I tried this on macOS I got an error message about `dukPy`. Did you get anything like this on Linux?

**Comment by tetron** [comment]
On Linux, I get a folder `build/benten-ls` which had a `benten-ls` executable along with a bunch of libraries and a zipfile of additional code.  Confusingly, most (all?) of the actual `benten` code is included directly in the `benten-ls` execution.  I'm pretty sure we'll want to distribute the entire `build/benten-ls` folder.

However, on Linux, I think building distribution packages with `fpm` are going to be much preferred over PyInstaller.  So we should focus on MacOS and Windows.

Could you paste the `dukPy` error?

**Comment by kaushik-work** [comment]
```
(rabix) c02cr2e3ml85@MacBook-Pro benten % ./dist/benten-ls/benten-ls
Traceback (most recent call last):
  File "benten-ls.py", line 1, in <module>
    import benten.__main__
  File "/Users/c02cr2e3ml85/.venvs/rabix/lib/python3.9/site-packages/PyInstaller/loader/pyimod03_importers.py", line 493, in exec_module
    exec(bytecode, module.__dict__)
  File "benten/__main__.py", line 7, in <module>
    from .configuration import Configuration
  File "/Users/c02cr2e3ml85/.venvs/rabix/lib/python3.9/site-packages/PyInstaller/loader/pyimod03_importers.py", line 493, in exec_module
    exec(bytecode, module.__dict__)
  File "benten/configuration.py", line 8, in <module>
    from .cwl.specification import parse_schema
  File "/Users/c02cr2e3ml85/.venvs/rabix/lib/python3.9/site-packages/PyInstaller/loader/pyimod03_importers.py", line 493, in exec_module
    exec(bytecode, module.__dict__)
  File "benten/cwl/specification.py", line 8, in <module>
    from .alltypes import *
  File "/Users/c02cr2e3ml85/.venvs/rabix/lib/python3.9/site-packages/PyInstaller/loader/pyimod03_importers.py", line 493, in exec_module
    exec(bytecode, module.__dict__)
  File "benten/cwl/alltypes.py", line 12, in <module>
    from .expressiontype import CWLExpressionType
  File "/Users/c02cr2e3ml85/.venvs/rabix/lib/python3.9/site-packages/PyInstaller/loader/pyimod03_importers.py", line 493, in exec_module
    exec(bytecode, module.__dict__)
  File "benten/cwl/expressiontype.py", line 6, in <module>
    import dukpy
ModuleNotFoundError: No module named 'dukpy'
[86658] Failed to execute script benten-ls
```

**Comment by tetron** [comment]
Ok I got `dist/` and `build/` confused.  There are some useful log files in `build/` but `dist/` is where it puts thing that is supposed to be runnable.

Hm, maybe it didn't include 'dukpy' in the package?  

Maybe there's useful information in `build/benten-ls/warn-benten-ls.txt`

What version of Python and PyInstaller are you using?

**Comment by tetron** [comment]
1. I set up a Windows 2016 VM and connected with remote desktop
2. I managed to install python, git, vscode etc
3. PyInstaller successfully created a working `benten-ls.exe`
4. My idea is for the Windows (and MacOS?) installer to place the benten package in `$HOME/.local/lib/benten/bin`
5. Then the vsCode extension can add `$HOME/.local/lib/benten/bin` to its search path for `benten-ls`

**Comment by tetron** [comment]
The even more clever thing to do would be to sniff the OS and download the appropriate binary from within the language client so there is no extra step

**Comment by tetron** [comment]
Superceded by #103

**Pull request closed without merging**
